baseURL = "https://gokhanarkan.com"
title = "Gökhan Arkan"
theme = "etch"
languageCode = "en-gb"
enableInlineShortcodes = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[params]
  description = "Personal landing page of Gökhan Arkan"
  copyright = "Have a great day!"
  dark = "auto"
  highlight = true

[permalinks]
  posts = "/:title/"

[markup.goldmark.renderer]
  # Allow HTML in Markdown
  unsafe = true

  [markup.tableOfContents]
    ordered = true
